# Generated by Django 2.2.5 on 2019-10-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationuser',
            name='group',
        ),
    ]
