# Generated by Django 2.2.9 on 2020-01-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_generationuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationuser',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
