# Generated by Django 2.2.5 on 2019-11-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmessage',
            options={},
        ),
        migrations.AlterField(
            model_name='taskmessage',
            name='message',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
