# Generated by Django 2.2.5 on 2019-11-22 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Задача', max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_on', models.DateField()),
                ('task_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.Task')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
